### ISSUE TITLE
Regression: Memchr not compatible with no_std (since 834d442)

### ISSUE THREAD

**Issue by CWood1** [Geal/nom#514]
Memchr relies on libc, which is not available in a no_std context. The result is the following error:

```
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-none` target may not be installed

error: aborting due to previous error

error: Could not compile `libc`.
```

**Comment by Geal** [comment]
try to compile with `default-features = false" ?

**Comment by CWood1** [comment]
I attempted to compile nom with `default-features = false`, unfortunately I don't believe there's a way to influence the libc compilation. If I go one commit before, it works perfectly, though does indeed give the same error if I re-enable `default-features`.

**Comment by Geal** [comment]
I think with https://github.com/rust-lang/cargo/pull/712 (original idea here https://github.com/rust-lang/cargo/issues/633#issuecomment-59089252 ) it can be achievable.
I probably won't have the time to test this until thursday, would you be willing to test and make a patch for it?

**Comment by CWood1** [comment]
Sure, I'll take a look into that over the next day or two. Thanks for your help, I'll report back here after my investigations.

**Comment by Geal** [comment]
your fix is released in nom 3.1, thank you for your help!
