### ISSUE TITLE
do_parse! does not work with CompleteByteSlice in nom 4.0.0-beta1

### ISSUE THREAD

**Issue by hjr3** [Geal/nom#703]
The `do_parse!` combinator does not accept the `CompleteByteSlice` type. The following code:

```rust
fn foo(input: CompleteByteSlice) -> IResult<CompleteByteSlice, Vec<u32>> {
    many1!(input, bar)
}

fn bar(input: CompleteByteSlice) -> IResult<CompleteByteSlice, u32> {
    do_parse!(
        input,
        v: hex_u32 >>
        space >>

        (v)
    )
}

let input = b"6dcad223 000000001 ";
let _ = foo(CompleteByteSlice(input)).unwrap();
```

Gives this error when I compile:

```
error[E0308]: mismatched types
   --> src/main.rs:288:9
    |
288 | /         do_parse!(
289 | |             input,
290 | |             v: hex_u32 >>
291 | |             space >>
292 | |
293 | |             (v)
294 | |         )
    | |_________^ expected &[u8], found struct `nom::types::CompleteByteSlice`
    |
    = note: expected type `&[u8]`
               found type `nom::types::CompleteByteSlice<'_>`
```

I have tried to convert it to use `AsBytes` trait, but then I get a lifetime error:

```rust
fn foo(input: CompleteByteSlice) -> IResult<CompleteByteSlice, Vec<u32>> {
    many1!(input, bar)
}

fn bar(input: CompleteByteSlice) -> IResult<CompleteByteSlice, u32> {
    match do_parse!(
        input.as_bytes(),
        v: hex_u32 >>
        space >>

        (v)
    ) {
        Ok((remaining, value)) => Ok((CompleteByteSlice(remaining), value)),
        Err(Err::Incomplete(needed)) => Err(Err::Incomplete(needed)),
        Err(Err::Error(Context::Code(input, code))) => {
            Err(Err::Error(Context::Code(CompleteByteSlice(input), code)))
        }
        Err(Err::Failure(Context::Code(input, code))) => {
            Err(Err::Failure(Context::Code(CompleteByteSlice(input), code)))
        }
    }
}

let input = b"6dcad223 000000001 ";
let _ = foo(CompleteByteSlice(input)).unwrap();

```

```
error[E0597]: `input` does not live long enough
   --> src/main.rs:289:13
    |
289 |             input.as_bytes(),
    |             ^^^^^ borrowed value does not live long enough
...
304 |     }
    |     - borrowed value only lives until here
    |
note: borrowed value must be valid for the anonymous lifetime #1 defined on the function body at 287:5...
   --> src/main.rs:287:5
    |
287 | /     fn bar(input: CompleteByteSlice) -> IResult<CompleteByteSlice, u32> {
288 | |         match do_parse!(
289 | |             input.as_bytes(),
290 | |             v: hex_u32 >>
...   |
303 | |         }
304 | |     }
    | |_____^
```

The only way I could get this to work is to clone the value before using it in `do_parse!`. Unfortunately, this also means that `do_parse!` returns `Err::Incomplete` and I have to do a manual check for length:

```rust
fn foo(input: CompleteByteSlice) -> IResult<CompleteByteSlice, Vec<u32>> {
    many1!(input, bar)
}

fn bar(input: CompleteByteSlice) -> IResult<CompleteByteSlice, u32> {
    if input.as_bytes().len() == 0 {
        return Err(Err::Error(Context::Code(input, ErrorKind::Eof)));
    }

    let i = input.0.clone();
    match do_parse!(
        i,
        v: hex_u32 >>
        space >>

        (v)
    ) {
        Ok((remaining, value)) => Ok((CompleteByteSlice(remaining), value)),
        Err(Err::Incomplete(needed)) => Err(Err::Incomplete(needed)),
        Err(Err::Error(Context::Code(input, code))) => {
            Err(Err::Error(Context::Code(CompleteByteSlice(input), code)))
        }
        Err(Err::Failure(Context::Code(input, code))) => {
            Err(Err::Failure(Context::Code(CompleteByteSlice(input), code)))
        }
    }
}

let input = b"6dcad223 000000001 ";
let _ = foo(CompleteByteSlice(input)).unwrap();
```

**Comment by alexbool** [comment]
@Geal this is unfortunate, I also think nom's macro codebase should be audited for other places where input type cannot be specified

**Comment by Geal** [comment]
@alexbool I had already answered privately that the issue came from `hex_u32`  which only accepts `&[u8] `  right now. So `do_parse` is fine, specifically because it does not need to specify the input type.
Feel free to send a PR to fix `hex_u32`, I unfortunately don't have the time to do it right now.

**Comment by alexbool** [comment]
@Geal thanks for quick reply!
