### PR TITLE
Remove stabilized `alloc` feature gate.

### LINKED ISSUE #1038: Allow `alloc` feature to compile on stable with nom 6.0
Rustc v1.36.0 stabilized `extern crate alloc` and therefore the `alloc` feature gate is no longer necessary. Removing it would allow to compile `nom` with `alloc` feature and `no_std` mode on stable.

As nom currently defines rustc v1.31 as minimal supported version this is most likely a request for an upcoming nom 6.0.

----

- Rust version : rustc 1.38.0 (625451e37 2019-09-23)
- nom version : ^5.0
- nom compilation features used: {default-features = false, features = [ "alloc" ] }

```bash
> cargo build --no-default-features
   Compiling nom v5.0.1
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.0.1/src/lib.rs:402:59
    |
402 | #![cfg_attr(all(not(feature = "std"), feature = "alloc"), feature(alloc))]
    |                                                           ^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `nom`.

To learn more, run the command again with --verbose.
```

### PR DESCRIPTION
**Pull request by 0ndorio**
**Metadata**

related to: #1038 
required rustc version bump: from v1.31 to v1.36

**Content**

The `alloc` feature got stabilized in rustc v1.36 and it is therefore possible to remove the feature gate and compile the crate with `alloc` feature enabled with the stable toolchain.

... fixes #1038

### CODE REVIEW

**Comment by thequux** [comment]
Is anything blocking this? It would be really nice to be able to build no_std crates that use nom with stable rust.

**Comment by Geal** [comment]
this will go in nom 6 since it raises the minimum Rust version

**Comment by Geal** [comment]
wait, as you said in https://github.com/Geal/nom/issues/1038#issuecomment-558131986 this would only afect nightly Rust versions, so it should be safe to remove the feature gate

**Comment by richardanaya** [comment]
This is blocking me

**Comment by Geal** [comment]
thanks!
