### ISSUE TITLE
Allow `alloc` feature to compile on stable with nom 6.0

### ISSUE THREAD

**Issue by 0ndorio** [Geal/nom#1038]
Rustc v1.36.0 stabilized `extern crate alloc` and therefore the `alloc` feature gate is no longer necessary. Removing it would allow to compile `nom` with `alloc` feature and `no_std` mode on stable.

As nom currently defines rustc v1.31 as minimal supported version this is most likely a request for an upcoming nom 6.0.

----

- Rust version : rustc 1.38.0 (625451e37 2019-09-23)
- nom version : ^5.0
- nom compilation features used: {default-features = false, features = [ "alloc" ] }

```bash
> cargo build --no-default-features
   Compiling nom v5.0.1
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/rnd/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.0.1/src/lib.rs:402:59
    |
402 | #![cfg_attr(all(not(feature = "std"), feature = "alloc"), feature(alloc))]
    |                                                           ^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `nom`.

To learn more, run the command again with --verbose.
```

**Comment by fkrull** [comment]
This would only impact nightly versions < 1.36, wouldn't it? Stable would still work back to 1.31 since "alloc" didn't work there in the first place.

**Comment by 0ndorio** [comment]
> This would only impact nightly versions < 1.36, wouldn't it? Stable would still work back to 1.31 since "alloc" didn't work there in the first place.

You are right. Until `1.36` the feature wasn't available for stable builds so this should results in same situation for stable releases back to `1.31`.
