### ISSUE TITLE
nom 5.1.2 does not build on rust < 1.40 because of memchr

### ISSUE THREAD

**Issue by ericseppanen** [Geal/nom#1313]
```
$ rustup default 1.38
$ cargo new test_nom; cd test_nom
```
add the following to `Cargo.toml`:
```
[dependencies]
nom = "5.1.2"
```
Now it won't build:
```
$ cargo check
    Updating crates.io index
  Downloaded lexical-core v0.7.6
  Downloaded arrayvec v0.5.2
  Downloaded static_assertions v1.1.0
   Compiling bitflags v1.2.1
   Compiling ryu v1.0.5
   Compiling lexical-core v0.7.6
   Compiling version_check v0.9.3
   Compiling memchr v2.4.0
    Checking arrayvec v0.5.2
    Checking cfg-if v1.0.0
    Checking static_assertions v1.1.0
   Compiling nom v5.1.2
error[E0658]: non exhaustive is an experimental feature
   --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.4.0/src/memmem/prefilter/mod.rs:152:1
    |
152 | #[non_exhaustive]
    | ^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to previous error
```

**Comment by ericseppanen** [comment]
Locking `memchr` to 2.3.4 fixes the problem. For example, in my test crate, this works:
```
[dependencies]
memchr = "=2.3.4"
nom = "5.1.2"
```

**Comment by ericseppanen** [comment]
Confirmed that this patch allows nom to build on 1.37:
```
 [dependencies.memchr]
-version = "^2.0"
+version = ">= 2.0, < 2.4"
```

The documented msrv of 1.31 would require more changes:
```
 [dependencies.lexical-core]
-version = ">= 0.6, < 0.8"
+version = "~0.6"
```

lexical-core 0.7 was deliberately allowed in e73a4d40257, so that change might make someone unhappy. But either that would need to change, or the nom msrv would.

**Comment by Geal** [comment]
Hello, could you tell me more about why you need to use nom 5 instead of the latest version? I usually do not do maintenance on older versions, but if needed, we can discuss a support contract

**Comment by ericseppanen** [comment]
I don't *need* to use nom 5, but I generally expect that if I come back to old code and try to build it 7 months later, it should still compile.

I have a downstream crate (that's not widely used) which lists nom 5.1 as a dependency, and has a CI job that tests whether the code builds on Rust 1.37. This was a safe choice at the time, because nom 5.1 lists Rust 1.31 as its msrv. I noticed that my Rust 1.37 CI builds started failing even though I made no code changes, so I tracked it down to the packages above.

I understand that some package maintainers don't think that MSRV changes are a semver-breaking change, so all I can do is document for others where the problem originates and how to fix it. If upstream crates want to fix it, great, but even if not at least other users can find the github issue and learn how to fix it themselves.

**Comment by Geal** [comment]
I apply that same policy, and you'll see that nom 6.2 got the memchr version fix to keep the guarantee of 1.44 MSRV, and 1.37 with some features disabled.
But you cannot expect to get fixes to nom 5.1.2, which was released a year ago, while nom 6 has been available for 8 months (6 releases in that major version). I only maintain the latest version.
Can I suggest vendoring the dependency of your project? Or at least try crate replacement? That might be enough to keep it going.

**Comment by ericseppanen** [comment]
I do not expect support; I didn't see any documentation of how long previous major versions of nom are maintained, so I figured it couldn't hurt to open an issue. (Mostly so that anyone else with the same problem can save time in fixing their code.)

I apologize if my message gave the impression I expect you to do any work on this. I wrote up the fix above if anyone else wants it. If nom 5.1 is unsupported and will not accept changes, I am perfectly fine with that.

FWIW, vendoring doesn't seem necessary, at least in my case; I [worked around the problem](https://github.com/ericseppanen/cddl-cat/commit/9a5d25edbc0d1804c49cb460a8a2350b715e0afa) by pinning `memchr` to `2.3.4` in my crate dependencies.
